FROM node:16.5.0-alpine
WORKDIR /app
ENV NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true \
    NEW_RELIC_LOG=stdout \
    NEW_RELIC_ALLOW_ALL_HEADERS=true \
    NEW_RELIC_ENABLED=true \
    NEW_RELIC_LOG_LEVEL=info \
    NEW_RELIC_API_CUSTOM_EVENTS=true \
    NEW_RELIC_ERROR_COLLECTOR_ENABLED=true \
    NEW_RELIC_BROWSER_MONITOR_ENABLE=true \
    NEW_RELIC_SPAN_EVENTS_ENABLED=true \
    NEW_RELIC_APPLICATION_LOGGING_ENABLED=true \
    NEW_RELIC_APPLICATION_LOGGING_METRICS_ENABLED=true \
    NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=true 

COPY package*.json ./
RUN npm install

RUN npm cache clean --force
COPY . .
CMD npm run start
EXPOSE 3000
